### ISSUE TITLE
Delete zotero-key and zt-attachments

### ISSUE THREAD

**Issue by mai0503** [PKM-er/obsidian-zotlit#297]
Hi,

this plugin is very useful for me. Thanks for providing this tool. Now I have a question about eta template for generating notes automatically in obsidian. I don't need to show "zotero-key" and "zt-attachments" in the generated note. But I don't have a way to delete them in the field.eta file. 

kind regards

**Comment by Adonis2018** [comment]
I have the same issue, my zotero-key and the name of the folder where my document pdf is located are inconsistent

**Comment by Tylannn** [comment]
I guess it's a mark to connect with zotero items, but I wish to add this option for decoupling notes and source.

**Comment by zzhixin** [comment]
If you delete these two properties manually, it seems that nothing wrong happens. So I think it should be easy to remove it.

**Comment by Silence2540** [comment]
using custom CSS snippets to hide them：
```css
.metadata-property[data-property-key="zotero-key"],
.metadata-property[data-property-key="zt-attachments"] {
    display: none;
}
```
